repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: check-sfdx
        name: Check Salesforce DX
        entry: devops-scripts/precommit.sh
        language: script
        files: \.xml$