name: SFDX Scanner and Comment

on:
  pull_request:

jobs:
  pmd-analyser-check:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: pmd
        uses: Alfresco/alfresco-build-tools/.github/actions/pmd@ref
        with:
           pmd-version: "7.1.0" # The version of PMD to use (only 7.x versions are supported).
           create-github-annotations: "true" # Whether to create annotations using the GitHub Advanced Security (nb. this is not free for private repositories)
           pmd-ruleset-path: "config/scanner/pmd_config.xml" # The path to the PMD ruleset file from the root of the ruleset project. Optionally other paths to local rulesets can be appended to this separated by commas.
