name: Custom Scanner PMD

on:
  pull_request:
      types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: actions/github-script@v6
        with:
         script: |
            // Fetch files modified in the PR
            const pulledFiles = await github.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            });
            return pulledFiles;
