name: Custom Scanner PMD

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Scan Results
    env:
      PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
      PULL_REQUEST_BASE_REF: "${{ github.event.pull_request.base.ref }}"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SFDX Code Analyser

        run: |
          sf plugins install @salesforce/sfdx-scanner@4.2.0
          chmod +x ./devops-scripts/scan-pull-request.sh
          ./devops-scripts/scan-pull-request.sh

      - name: Add comment to PR files
        run: node devops-scripts/addScanComment.js

#      - name: Add comment to PR files
#        uses: actions/github-script@v7
#        with:
#          script: |
