name: SFDX Scanner and Comment

# Definition when the workflow should run
on:
  pull_request:

# Jobs to be executed when the above conditions are met
jobs:
  # This is the name of the job. You can give it whatever name you want
  Run-PMD-Code-Scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      # only required for workflows in private repositories
      actions: read

    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:

      # Now we install nodejs in the VM, and specify version 14
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run PMD Scan
      - name: 'Run PMD Scan'
        uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          sourcePath: 'src'
          rulesets: 'config/scanner/pmd_config.xml'
          analyzeModifiedFilesOnly: true
          createGitHubAnnotations: true

      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
