# Changelog will be written to changelog branch

name: 'Test includeChangedESIntoPackage.sh in pr run'

on:
  workflow_dispatch:

jobs:
  deploy-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SKIP_ORG_INTERACTION: ${{ vars.SKIP_ORG_INTERACTION }}
      # Sets the deployment destination from sfdx-project.json
      SF_APPLY_REPLACEMENTS_ON_CONVERT: ${{ vars.SF_APPLY_REPLACEMENTS_ON_CONVERT }}
      DEPLOY_DESTINATION: ${{ vars.DEPLOY_DESTINATION }}
      MANUAL_WORKFLOWS: ${{ vars.MANUAL_WORKFLOWS }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: es
        id: es
        run: |
          echo "Pr"
          chmod +x ./devops-scripts/includeChangedESIntoPackage.sh
          ./devops-scripts/includeChangedESIntoPackage.sh
