# Changelog will be written to changelog branch

name: 'Manual Deployment'

on:
  workflow_dispatch:
    inputs:
      modules_to_deploy:
        description: List of modules to deploy (space separated). If left blank then all modules will get deployed
        type: string
      environment:
        description: Environment
        type: environment
        required: true
jobs:
  deploy-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      ${{ github.event.inputs.environment }}
    env:
      SKIP_ORG_INTERACTION: ${{ vars.SKIP_ORG_INTERACTION }}
      # Sets the deployment destination from sfdx-project.json
      SF_APPLY_REPLACEMENTS_ON_CONVERT: ${{ vars.SF_APPLY_REPLACEMENTS_ON_CONVERT }}
      DEPLOY_DESTINATION: ${{ vars.DEPLOY_DESTINATION }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy Changes to ${{ github.event.inputs.environment }}
        id: deploy_changes
        run: |
          chmod +x ./devops-scripts/runDeployments.sh 
          ./devops-scripts/runDeployments.sh ${{ github.event.inputs.modules_to_deploy }}
          
      - name: Cancel Job
        run: |
          chmod +x ./devops-scripts/cancelJob.sh
          ./devops-scripts/cancelJob.sh  ${{steps.deploy_changes.outputs.deployment_id}}