name: 'Push to main branch - Deploy to PROD'
on:
  push:
    branches:
      - main

jobs:
  deploy-changes:
    runs-on: ubuntu-latest
    env:
      SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
    environment: 'PROD'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli@${SF_CLI_VERSION} --global

      - name: Authenticate
        id: auth
        env:
          SFDXAUTHURL: ${{secrets.SFDX_AUTH_URL}}
        run: |
          chmod +x ./devops-scripts/authenticate.sh
          ./devops-scripts/authenticate.sh --set-default

      - name: Deploy Changes to PROD
        id: deploy_changes
        run: |
          git config --global --add safe.directory "*"
          chmod +x ./devops-scripts/runDeployments.sh 
          ./devops-scripts/runDeployments.sh

      - name: Cancel Job
        id: cancel
        if: ${{ cancelled() }}
        run: |
          chmod +x ./devops-scripts/cancelJob.sh
          ./devops-scripts/cancelJob.sh  ${{steps.deploy_changes.outputs.deployment_id}}