name: Push to Release Branch PoC
on:
  push:
    branches:
      - release/*
      - chore/release-automation
  workflow_dispatch:

jobs:
  deploy-to-homes-sit:
    name: Deploy to HomesSIT
    uses: ./.github/workflows/deploy-manual.yml
    with:
      environment: 'HomesSIT'
    secrets: inherit

  deploy-to-homes-qa:
    name: Deploy to HomesQA
    needs:
      - deploy-to-homes-sit
    uses: ./.github/workflows/deploy-manual.yml
    with:
      environment: 'HomesQA'
    secrets: inherit

  deploy-to-pre-prod:
    name: Deploy to Pre-PROD
    needs:
      - deploy-to-homes-qa
    uses: ./.github/workflows/deploy-manual.yml
    with:
      environment: 'PRE-PROD'
    secrets: inherit
