# Changelog will be written to changelog branch

name: 'Push to develop branch - Deploy to MaxQA'

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'src/**'
jobs:
  deploy-to-maxqa:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      # Sets the deployment destination from sfdx-project.json
      SF_APPLY_REPLACEMENTS_ON_CONVERT: ${{ vars.SF_APPLY_REPLACEMENTS_ON_CONVERT }}
      DEPLOY_DESTINATION: ${{ vars.DEPLOY_DESTINATION }}
      # Sets the allowed modifications to be controlled by DevOps team members
      ALLOWED_DEV_MODIFICATIONS: ${{ vars.ALLOWED_DEV_MODIFICATIONS }}
      DEVOPS_TEAM: ${{ vars.DEVOPS_TEAM }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Changed Packages
        id: detect_changes
        run: |
          chmod +x ./devops-scripts/findChangedModules.sh
          ./devops-scripts/findChangedModules.sh HEAD^   #compare changes vs previous commit in develop branch

      - name: Forceignore
        run: |
          chmod +x ./devops-scripts/esExclude.sh
          ./devops-scripts/esExclude.sh HEAD^   #compare changes vs previous commit in develop branch

