name: 'Download QMS data'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment from where QMS data will be downloaded
        type: environment
  workflow_call:
    inputs:
      environment:
        description: Environment from where QMS data will be downloaded
        type: string

jobs:
  download-qms-data:
    name: 'Download QMS Data'
    runs-on: ubuntu-latest
    env:
      SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
    environment:
      ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli@${SF_CLI_VERSION} --global

      - name: Authenticate ${{ inputs.environment }}
        env:
          SFDXAUTHURL: ${{secrets.SFDX_AUTH_URL}}
        run: |
          chmod +x ./devops-scripts/authenticate.sh
          ./devops-scripts/authenticate.sh "--set-default --alias target-org"

      - name: Download QMS Data
        run: |
          chmod +x ./devops-scripts/qms/downloadQmsData.sh
          ./devops-scripts/qms/downloadQmsData.sh target-org

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 7
          name: qms-data
          path: ./data/qms

