# Script is executable by schedule. At each run it scans all modules and stores scanning results as artifacts in CI jobs

name: Exp Set

on:
  push:
    branches:
      - 'develop'

jobs:
  code_scanner:
    runs-on: ubuntu-latest
    name: Daily Code Scan
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dep
        run: npm install xml2js child_process

      - name: Run develop
        run: |
          cat sourcePackage.xml
          git config --global --add safe.directory "*"
          node devops-scripts/deployExpressionSets.js
          cat sourcePackage.xml

