# Script is executable by schedule. At each run it scans all modules and stores scanning results as artifacts in CI jobs

name: Exp Set

on:
  push:
    branches:
      - 'develop'

jobs:
  code_scanner:
    runs-on: ubuntu-latest
    name: Daily Code Scan
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dep
        run: npm install yargs-parser child_process

      - name: Run develop
        run: node devops-scripts/test.js --base-branch '^HEAD'

