# Script is executable by schedule. At each run it scans all modules and stores scanning results as artifacts in CI jobs

name: Exp Set

on:
  workflow_dispatch:

jobs:
  code_scanner:
    runs-on: ubuntu-latest
    name: Daily Code Scan
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dep
        run: npm install xml2js child_process

      - name: Install SFDX Code Analyser
        run: |
          git config --global --add safe.directory /__w/Santander-2/Santander-2
          node devops-scripts/deployExpressionSets.js