name: FindChangedModules

on:
    pull_request:
        types: [opened, reopened, synchronize, edited]

jobs:
    my_job:
        runs-on: ubuntu-latest
        env:
            DEVOPS_TEAM: ${{ vars.DEVOPS_TEAM }}
            ALLOWED_DEV_MODIFICATIONS: ${{ vars.ALLOWED_DEV_MODIFICATIONS }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Turn comment into file
              run: |
                  echo "start findChangedModules"
                  chmod +x ./devops-scripts/findChangedModules.sh 
                  ./devops-scripts/findChangedModules.sh
