name: CI Reporting

on:
  push:
    branches: ["main"]
#  schedule:
#  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scan_1:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           echo "GIT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          else
           GIT_BRANCH=${{ github.ref }}
           GIT_BRANCH=${GIT_BRANCH#refs/heads/}
           echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
         fi

      - name: Install Scanner
        run: sf plugins install @salesforce/sfdx-scanner@latest-beta

      - name: Run Scanner
        id: scanner
        run: |         
          chmod +x ./bash.sh
          ./bash.sh

      - name: Show Scan Results
        run: |
          cat output/report.html >> $GITHUB_STEP_SUMMARY

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Daily Scan Results in HTML
          path: output/*/*.html
