name: Check deployments

on:
  pull_request:
    branches:
      - develop
      - feature/deploy-test

jobs:
  scan_1:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4