name: Check deployments

on:
  pull_request:
    branches:
      - develop
      - feature/deploy-test

jobs:
  scan_1:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Create data packages for new, modified or deleted metadata
      
        run: |
          echo y | sf plugins:install sfdx-git-delta
          git config --global --add safe.directory "*"
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output ./src --source src/
          chmod +x scripts/changedModules.sh
          scripts/changedModules.sh
          chmod +x scripts/runDeployment.sh
          scripts/runDeployment.sh "${module_array[@]}"
#          Find Changed Modules
        env:
          GITHUB_OUTPUT: $GITHUB_ENV  # Redirect GITHUB_OUTPUT to a known environment variable
          SKIP_ORG_INTERACTION: false
          
