name: CI Reporting

on:
  push:
    branches: ["main"]
#  schedule:
#  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scan_1:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
         export GITHUB_REPOSITORY="${{ github.repository }}"
         if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          GIT_BRANCH="${{ github.head_ref }}"
         else
          GIT_BRANCH="${{ github.ref#refs/heads/ }}"
         fi
         echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Install Scanner
        run: sf plugins install @salesforce/sfdx-scanner@latest-beta

      - name: Run Scanner
        id: scanner
        run: |
          export GITHUB_REPOSITORY="${{ github.repository }}"
          export GIT_BRANCH="${{ env.GIT_BRANCH }}"
          chmod +x ./bash.sh
          ./bash.sh

      - name: Show Scan Results
        run: |
          cat output/report.html >> $GITHUB_STEP_SUMMARY

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Daily Scan Results in HTML
          path: output/*/*.html
