name: Check deployments

on:
  pull_request:
    branches:
      - develop

jobs:
  scan_1:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Install SFDX GitDelta Plugin
        run: echo y | sf plugins:install sfdx-git-delta

      - name: Create data packages for new, modified or deleted metadata
        run: |
          git config --global --add safe.directory /__w/mortgagesfdc-homes-crm/mortgagesfdc-homes-crm 
          sf sgd:source:delta --to "HEAD" --from "HEAD^" --output ./src --source src/

      - name: Find Changed Modules
        id: find_changed_modules
        run: |
          chmod +x ./scripts/changedModules.sh
          ./scripts/changedModules.sh origin/develop
        env:
          GITHUB_OUTPUT: $GITHUB_ENV  # Redirect GITHUB_OUTPUT to a known environment variable

      - name: Deploy Modules
        if: steps.find_changed_modules.outputs.changed_modules != ''
        run: |
          chmod +x ./scripts/runDeployment.sh
          # Read the changed_modules from the environment variable and convert to array
          IFS=',' read -r -a module_array <<< "${{ steps.find_changed_modules.outputs.changed_modules }}"
          ./scripts/runDeployment.sh "${module_array[@]}"
        env:
          SKIP_ORG_INTERACTION: false
