name: CI Reporting Artifact

on:
  push:
    branches: 'main'

jobs:
  scan_main:
    runs-on: ubuntu-latest
    name: Run Scanner
    container:
      image: salesforce/cli:latest-full
    outputs:
      output_path: ${{steps.scanner.outputs.output_directory}}
    steps:
      - uses: actions/checkout@v4

      - name: Install Scanner
        run: sf plugins install @salesforce/sfdx-scanner@latest-beta

      - name: Run Scanner
        id: scanner
        run: |
          export GITHUB_REPOSITORY_URL="${{ github.repositoryUrl }}"
          export GITHUB_REF_NAME="${{ github.ref_name }}"
          chmod +x ./bash.sh
          ./bash.sh
           cat output/report.html >> $GITHUB_STEP_SUMMARY
