name: Check deployments

on:
  pull_request

env:
  BROKER_PORTAL: broker-portal
  APPLICATION_LOGGING: application-logging

jobs:
  scan_1:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Deploy modules
        run: |
            echo "GITHUB_OUTPUT=${{ github.output }}" >> $GITHUB_ENV
            
            # Run the deployment script with the provided modules
            chmod +x ./scripts/runDeployment.sh
            ./scripts/runDeployment.sh "${module_array[@]}"
          
          
