name: PR Open

on:
  push:
#    types: [opened, reopened, synchronize]

    paths:
      - 'src/**'

jobs:
  validate-changes:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint and plugins
        run: npm install eslint @babel/core @babel/eslint-parser @lwc/eslint-plugin-lwc --save-dev

      - name: Run ESLint
        run: |
          echo "deploy-test-pr-branch"
          chmod +x ./scripts/reporting.sh
          ./scripts/reporting.sh
          
      - name: Show Scan Results
        run: |
          cat output/scanner_results.html >> $GITHUB_STEP_SUMMARY

#      - name: Deploy Lookup Tables
#        run: |
#          chmod +x ./scripts/newMatrixVersion.sh
#          ./scripts/newMatrixVersion.sh
