name: PR Open

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**'

jobs:
  validate-changes:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy Lookup Tables
      
        run: |
          echo "deploy-test branch"
          chmod +x ./scripts/newMatrixVersion.sh
          ./scripts/newMatrixVersion.sh
#          chmod +x scripts/runDeployment.sh
#          scripts/runDeployment.sh "${module_array[@]}"

