name: Get Team Members
on:
  workflow_dispatch:

jobs:
  check-user-in-team:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch team members
      id: fetch-members
      uses: actions/github-script@v5
      with:
        script: |
          const { org, team_slug } = process.env;
          const { data: members } = await github.request('GET /orgs/{org}/teams/{team_slug}/members', {
            org,
            team_slug
          });
          console.log(members.map(member => member.login));
          return members.map(member => member.login);
      env:
        GH_PAT: ${{ secrets.GH_TOKEN }}
        org: Onix-bash
        team_slug: general

