name: Get Team Members

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check if user is a team member
      id: check_membership
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/Onix-bash/teams/dev-team/memberships/Kristy-user)
        echo "HTTP_STATUS=$RESPONSE" >> $GITHUB_ENV
        echo "$RESPONSE"

    - name: Output result
      run: |
        if [ "${{ env.HTTP_STATUS }}" == "200" ]; then
          echo "User is a team member."
        else
          echo "User is not a team member."
        fi
