name: Get Team Members

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is in team
        id: check_user
        uses: actions/github-script@v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = 'Kristy-user';
            const team_slug = 'general';
            const org = 'Onix-bash';

            try {
              // GitHub API endpoint to check team membership
              const result = await github.rest.teams.getMembershipForUserInOrg({
                org,
                team_slug,
                username,
              });
              console.log('reasult', result);
              if (result.status === 200 && result.data.state === 'active') {
                core.setOutput('is_member', true);
              } else {
                core.setOutput('is_member', false);
              }
            } catch (error) {
              if (error.status === 404) {
                core.setOutput('is_member', false);
              } else {
                throw error;
              }
            }
