name: Get Team Members
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub Username to check'
        required: true
      team_slug:
        description: 'Team slug to check against'
        required: true

jobs:
  check_membership:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is in the specified team
        uses: actions/github-script@v6
        with:
          script: |
            const username = '${{ github.event.inputs.username }}';
            const team_slug = '${{ github.event.inputs.team_slug }}';
            const org = context.repo.owner; // Assumes the team is in the same org as the repo

            // Fetch team members from the GitHub API
            try {
              const teamMembers = await github.rest.teams.listMembersInOrg({
                org: org,
                team_slug: team_slug,
                per_page: 100 // Adjust depending on the expected team size
              });

              // Check if the specified user is in the team
              const isMember = teamMembers.data.some(member => member.login === username);
              
              if (isMember) {
                console.log(`${username} is a member of the team ${team_slug}`);
                core.setOutput("is_member", "yes");
              } else {
                console.log(`${username} is not a member of the team ${team_slug}`);
                core.setOutput("is_member", "no");
              }
            } catch (error) {
              core.setFailed(`Failed to fetch team members: ${error.message}`);
            }
          result-encoding: string
