name: Get Team Members

on:
  workflow_dispatch:

jobs:
  check-user-in-team:
    runs-on: ubuntu-latest
    steps:
      - name: Check User in Team
        uses: actions/github-script@v6
        with:
          script: |
            const teamName = 'general';
            const username = 'Kristy-user';

            const team = await github.rest.teams.getByName({
              org: context.repo.owner,
              team_slug: teamName
            });

            const members = await github.paginate(
              github.rest.teams.listMembersInOrg,
              {
                org: context.repo.owner,
                team_slug: team.data.slug,
                per_page: 100
              }
            );
            console.log(members);

            const userInTeam = members.some(member => member.login === username);

            if (userInTeam) {
              console.log(`User ${username} is part of the ${teamName} team.`);
            } else {
              console.log(`User ${username} is not part of the ${teamName} team.`);
            }
