name: Get Team Members

on:
  push
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Turn comment into file
      run: |
       DEV_OPS="${{ vars.DEV_OPS }}"
       chmod +x ./scripts/findChangedModules.sh 
       ./scripts/findChangedModules.sh "${DEV_OPS}"
