name: Get Team Members

on:
  pull_request:
   paths:
    - 'src/**'
jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
        DEV_OPS: ${{ vars.DEV_OPS }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Turn comment into file
      run: |
       echo "test-pr"
       chmod +x ./scripts/findChangedModules.sh 
       ./scripts/findChangedModules.sh 
