name: Get Team Members

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Turn comment into file
      run: |
       echo "${{ vars.DEV_OPS }}" >> $GITHUB_ENV
       chmod +x ./scripts/findChangedModules.sh 
       ./scripts/findChangedModules.sh 
