name: Get Team Members

on:
  push:
    branches:
      - main

jobs:
  get_team_members:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Team Members
        id: get-members
        uses: actions/github-script@v5
        with:
          script: |
            const org = 'your-org';
            const team_slug = 'your-team-slug';
            const teamMembers = [];

            const { data: team } = await github.rest.teams.getByName({
              org: org,
              team_slug: team_slug
            });

            const { data: members } = await github.rest.teams.listMembersInOrg({
              org: org,
              team_slug: team_slug
            });

            for (const member of members) {
              teamMembers.push({
                login: member.login,
                name: member.name,
                email: member.email
              });
            }

            console.log(teamMembers);
            
            return teamMembers;
 
