name: Get Team Members

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      DEVOPS_TEAM: ${{ vars.DEVOPS_TEAM }}
      ALLOWED_MODIFICATIONS: ${{ vars.ALLOWED_MODIFICATIONS }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Turn comment into file
      run: |
       chmod +x ./scripts/findChangedModules.sh HEAD^
       ./scripts/findChangedModules.sh 
