name: Get Team Members

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check if user is a team member
      id: check_membership
      run: |
        RESPONSE=$(curl -L \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \ 
         https://api.github.com/orgs/Onix-bash/teams/dev-team/memberships/Kristy-user)
        echo "HTTP_STATUS=$RESPONSE" >> $GITHUB_ENV
        echo "$RESPONSE"

    
