name: Get Team Members

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is in team
        id: check_user
        uses: actions/github-script@v6
        with:
          script: |
            const username = github.context.payload.inputs.username;
            const team_slug = github.context.payload.inputs.team_slug;
            const org = github.context.payload.inputs.org;
            const token = process.env.GITHUB_TOKEN;

            try {
              // GitHub API endpoint to check team membership
              const result = await github.rest.teams.getMembershipForUserInOrg({
                org,
                team_slug,
                username,
                headers: {
                  accept: 'application/vnd.github+json',
                  authorization: `token ${token}`
                }
              });
              console.log('result:' ,result);
              if (result.status === 200 && result.data.state === 'active') {
                core.setOutput('is_member', true);
              } else {
                core.setOutput('is_member', false);
              }
            } catch (error) {
            console.log('error:' , error);
              if (error.status === 404) {
                core.setOutput('is_member', false);
              } else {
                throw error;
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
