name: Get Team Members

on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is in team
        id: check_user
        uses: actions/github-script@v6
        with:
          script: |
            const username = 'kristina-klepik';
            const team_slug = 'Onix-bash';
            const org = 'dev-team';

            try {
              // GitHub API endpoint to check team membership
              const result = await github.rest.teams.getMembershipForUserInOrg({
                org,
                team_slug,
                username,
              });

              if (result.status === 200 && result.data.state === 'active') {
              console.log(result);
                core.setOutput('is_member', true);
              } else {
                core.setOutput('is_member', false);
              }
            } catch (error) {
            console.log(rerror);
              if (error.status === 404) {
                core.setOutput('is_member', false);
              } else {
                throw error;
              }
            }

      
