name: Get Team Members
on:
  workflow_dispatch:

jobs:
  check-user-in-team:
    runs-on: ubuntu-latest
    steps:
      - name: Check User in Team
        uses: actions/github-script@v6
        with:
          script: |
            const teamName = 'general';
            const username = 'kristina-klepik';
            const org = 'Onix-bash';

            const teams = await github.paginate(
              github.rest.teams.list,
              {
                org: org,
                per_page: 100
              }
            );

            const team = teams.data.find(t => t.name.toLowerCase() === teamName.toLowerCase());

            if (!team) {
              console.log(`Team ${teamName} not found in the organization.`);
              return;
            }

            const members = await github.paginate(
              github.rest.teams.listMembersInOrg,
              {
                org: org,
                team_slug: team.slug,
                per_page: 100
              }
            );

            const userInTeam = members.some(member => member.login === username);

            if (userInTeam) {
              console.log(`User ${username} is part of the ${teamName} team.`);
            } else {
              console.log(`User ${username} is not part of the ${teamName} team.`);
            }
