name: Get Team Members
on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login;
            const result = await github.rest.teams.getMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: 'general',
              username: creator
            });
            console.log(`User: ${creator}`);
            console.log(`Membership Status: ${result.data.state}`);
