name: JS Custom Scanner PMD

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get file list from PR
        id: get-pr-files
        uses: actions/github-script@v7
        with:
            script: |
              const { data: files } = await github.rest.pulls.listFiles({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number
              });
              
              // Join file names by comma
              const fileNames = files.map(file => file.filename).join(',');
              console.log('fileNames', fileNames);
              return { fileNames };

      - name: Install SFDX Code Analyser
        run: |
          sf plugins install @salesforce/sfdx-scanner@4.2.0
          npm install @salesforce/eslint-config-lwc @lwc/eslint-plugin-lwc @salesforce/eslint-plugin-lightning eslint-plugin-import eslint-plugin-jest

      - name: Run SFDX Scanner
        run: |
          mkdir -p "output"
          echo "Files changed: ${{ steps.get-pr-files.outputs.fileNames }}"
          sf scanner run --target ${{ steps.get-pr-files.outputs.fileNames }} --format json --pmdconfig ./config/scanner/pmd_config.xml --eslintconfig ./config/scanner/.eslintrc.json --outfile output/report.json

      - name: Add comment to PR files
        uses: actions/github-script@v7
        with:
            script: |
              const script = require('./devops-scripts/script-commit.js')
              await script({github, context})
