# Changelog will be written to changelog branch

name: 'Test Es in PR'

on:
  pull_request:

jobs:
  pr-validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MANUAL_WORKFLOWS: ${{ vars.MANUAL_WORKFLOWS }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

  get-ci-org-from-pool:
    name: Get CI-Org from Pool
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'specific_org') }}
    secrets: inherit
    with:
      environment: Scratch_Orgs
      ci_ref_branch: ${{ contains(github.event.pull_request.labels.*.name, 'specific_ref_branch') && github.head_ref || 'develop' }}

    uses: ./.github/workflows/get-org-from-pool.yml