# Changelog will be written to changelog branch

name: 'Test Es in PR'

on:
  pull_request:

jobs:
  pr-validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Es changes
        run: |
          chmod +x ./devops-scripts/includeChangesESIntoPackage.sh
          ./devops-scripts/includeChangesESIntoPackage.sh 

