
name: Action prettier

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          only_changed: True
          same_commit: True
          prettier_plugins: "prettier-plugin-apex @prettier/plugin-xml"
          prettier_options: "--write **/*.{js,css,html,cls,trigger} --ignore-unknown"