name: Prettier

on:
  workflow_dispatch:
    

jobs:
  prettier:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Prettier
        run: npm install --save-dev prettier prettier-plugin-apex @prettier/plugin-xml

      - name: Get list of changed files
        id: changed-files
        run: |
          git config --global --add safe.directory "*"
          chmod +x ./devops-scripts/findChangedPrFiles.sh
          ./devops-scripts/findChangedPrFiles.sh

      - name: Run Prettier
        id: prettier_check
        if: steps.changed-files.outputs.files != ''
        run: |
          npx prettier --write ${{ steps.changed-files.outputs.files }} --ignore-unknown
          modified_files=$(git diff --name-only --diff-filter=M | grep '^src/' | tr '\n' ' ')
          echo "files=$modified_files" >> "$GITHUB_OUTPUT"

      - name: Commit prettier changes
        if: steps.prettier_check.outputs.files != ''
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d
        with:
          commit_message: "Prettier code formatting"
          file_pattern: ${{ steps.prettier_check.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
