name: Prettier

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Prettier and Plugins
        run: npm install prettier prettier-plugin-apex @prettier/plugin-xml

      - name: Get list of changed files
        id: changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const githubContext = context;
            let files = [];
            if (githubContext.eventName === 'pull_request') {
              const prNumber = githubContext.payload.pull_request.number;
              const repoOwner = githubContext.repo.owner;
              const repoName = githubContext.repo.repo;
              const { data } = await github.rest.pulls.listFiles({
                owner: repoOwner,
                repo: repoName,
                pull_number: prNumber
              });
              files = data.filter(f => f.status !== 'removed');
            } else if (githubContext.eventName === 'workflow_dispatch') {
              // For manual runs, get the diff against the main branch
              const { execSync } = require('child_process');
              base_branch="origin/$(git remote show origin | grep 'HEAD branch' | sed 's/.*: //')"
              const diff = execSync('git diff --name-only $base_branch').toString().trim();
              files = diff.split('\n').filter(f => f.startsWith('src/'));
            }

            const fileNames = files.map(f => f.filename ? f.filename : f).join(' ');
            console.log('Files:', fileNames);
            core.setOutput('files', fileNames);
      - name: Run Prettier
        if: steps.changed-files.outputs.files != ''
        run: |
          files=${{ steps.changed-files.outputs.files }}
          echo "$files"
          npx prettier --write ${{ steps.changed-files.outputs.files }}
      - name: Commit changes
        if: steps.changed-files.outputs.files != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Prettier code formatting"
          file_pattern: ${{ steps.changed-files.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}