name: Prettier Manual

on:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Prettier and Plugins
        run: |
          npm install prettier prettier-plugin-apex @prettier/plugin-xml
          git config --global --add safe.directory /__w/Santander-2/Santander-2

      - name: Get list of changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            pr_number=${{ github.event.pull_request.number }}
            files=$(gh pr view $pr_number --json files --jq '.files[].path' | grep '^src/')
          else
            current_branch="origin/$(git branch --show-current)"
            base_branch="origin/$(git remote show origin | grep 'HEAD branch' | sed 's/.*: //')"
            git fetch origin
            files=$(git diff --name-only $base_branch...$current_branch | grep '^src/')
          fi
          files=$(echo "$files" | tr '\n' ' ')
          echo "Files: $files"
          echo "files=$files" >> "$GITHUB_OUTPUT"
      - name: Run Prettier
        if: steps.changed-files.outputs.files != ''
        run: |
          files=${{ steps.changed-files.outputs.files }}
          echo "$files"
          npx prettier --write ${{ steps.changed-files.outputs.files }} --ignore-unknown
      - name: Commit changes
        if: steps.changed-files.outputs.files != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Prettier code formatting"
          file_pattern: ${{ steps.changed-files.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}