name: JS Custom Scanner PMD

on:
  workflow_dispatch:
    inputs:
      modules_to_validate:
        description: List of modules to validate (space separated). If left blank then all modules will get validated
        type: string
#  pull_request:
#    types: [ opened, reopened, synchronize, edited]
#    paths:
#      - 'src/**'

jobs:
  validate-changes:
    name: CI Org Validation
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SEVERITY: ${{ vars.SEVERITY }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate SFDX health
        run: sf -v

      - name: Get Changed Packages
        id: detect_changes
        run: |
          chmod +x ./devops-scripts/findChangedModules.sh
          ./devops-scripts/findChangedModules.sh

      - name: Install SFDX Code Analyser
        run: sf plugins install @salesforce/sfdx-scanner@4.2.0

      - name: Run SFDX Code Analyser
        run: |
          chmod +x ./devops-scripts/test_violation.sh
          ./devops-scripts/test_violation.sh ${{steps.detect_changes.outputs.changed_modules}}

      - name: Show Scan Results on PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const script = require('./devops-scripts/script-commit.js')
            await script({ github, context });
