name: CI Reporting

on:
  push:
    branches: [ "main" ]
  #  schedule:
  #  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scan_1:
    runs-on: ubuntu-latest
    name: Scan Results
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4  

      - name: Install Scanner
        run: sf plugins install @salesforce/sfdx-scanner@latest-beta

      - name: Run Scanner
        id: scanner
        env:
          GITHUB_REPOSITORY: ${{ github.repository}}
          GIT_BRANCH: ${{ github.head_ref }}
        run: |
          chmod +x ./scripts/reporting.sh
          ./scripts/reporting.sh

      - name: Show Scan Results
        run: |
          cat output/scanner_results >> $GITHUB_STEP_SUMMARY

      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Daily Scan Results in HTML
          path: output/*/*.html
