name: Static Code Analysis on PR
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
jobs:
  code_scanner:
    runs-on: ubuntu-latest
    name: Daily Code Scan
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SFDX Code Analyser
        run: |
          sf plugins install @salesforce/sfdx-scanner@4.2.0
          npm install @salesforce/eslint-config-lwc @lwc/eslint-plugin-lwc @salesforce/eslint-plugin-lightning eslint-plugin-import eslint-plugin-jest

      - name: Run SFDX Scanner
        uses: mitchspano/sfdx-scan-pull-request@main
        with:
          pmdconfig: config/scanner/pmd-config.xml
          severity-threshold: 2
          engine: 'pmd'