name: Static Code Analysis on PR
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Github Be Dubious
        run: git config --global safe.directory '*'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SFDX CLI and Scanner
        run: sf plugins install @salesforce/sfdx-scanner@4.2.0

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          delete-resolved-comments: true
          report-mode: comments
          pmdconfig: config/scanner/pmd_config.xml
          severity-threshold: 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
