name: Static Code Analysis on PR
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
jobs:
  apex:
    runs-on: ubuntu-latest
    name: Daily Code Scan
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: APEX delta scan
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          pmdconfig: config/scanner/pmd_config.xml