name: Static Code Analysis on PR
on:
#  pull_request:
#    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - uses: actions/checkout@v4

      - name: Install SFDX CLI and Scanner
        run: |
          git config --global --add safe.directory "*"
          sf plugins install @salesforce/sfdx-scanner@4.2.0

      - name: SFDX Scan Pull Request
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          pmdconfig: config/scanner/pmd_config.xml
          severity-threshold: 2
          report-mode: comments
          delete-resolved-comments: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
