# Script is executable by schedule. At each run it scans all modules and stores scanning results as artifacts in CI jobs

name: Daily Run Apex Unit Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily
  workflow_call:

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    env:
      SF_CLI_VERSION: ${{ vars.SF_CLI_VERSION }}
    name: Daily Code Scan
    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli@${SF_CLI_VERSION} --global

      - name: Authenticate
        id: auth
        env:
          SFDXAUTHURL: ${{secrets.SFDX_AUTH_URL_MAX_QA}}
        run: |
          chmod +x ./devops-scripts/authenticate.sh
          ./devops-scripts/authenticate.sh "--set-default --alias MaxQA"

      - name: Run Apex Unit Tests
        id: deploy_changes
        run: sf apex run test --test-level RunAllTestsInOrg --wait 10 --target-org MaxQA
