name: Compare Retrieved Metadata with Branch

on:
  pull_request:

jobs:
  compare-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compare Metadata Directories
        id: ci_org_es_changes
        run: |
          git config --global --add safe.directory "*"
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "$current_branch"
          git fetch origin
          git checkout origin/develop
          branch_start=$(git branch --show-current)
          echo "$branch_start"
          echo "start findScratchChanges"
          chmod +x ./devops-scripts/findScratchChanges.sh
          ./devops-scripts/findScratchChanges.sh
          echo "$current_branch"
          git checkout -- .
          echo "checkout"
          git checkout "$current_branch"
          branch_finish=$(git branch --show-current)
          echo "$branch_finish"

      - name: Handle Changes
        run: |
          if [ -n "${{ steps.ci_org_es_changes.outputs.changed_files }}" ]; then
            echo "start addEsFromScratch"
            chmod +x ./devops-scripts/addEsFromScratch.sh
            ./devops-scripts/addEsFromScratch.sh "${{ steps.compare_dirs.outputs.changed_files }}"
          fi