name: Compare Retrieved Metadata with Branch

on:
  pull_request:

jobs:
  compare-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compare Metadata Directories
        run: |
          git config --global --add safe.directory "*"
          echo "current_branch=$(git branch --show-current)" >> $GITHUB_ENV
          git fetch origin
          git checkout develop
          branch_start=$(git branch --show-current)
          echo "$branch_start"
          echo "start findScratchChanges"
          chmod +x ./devops-scripts/findScratchChanges.sh
          ./devops-scripts/findScratchChanges.sh
          git checkout -- .
          git checkout $current_branch
          if [ -n "$changed_files" ]; then
          chmod +x ./devops-scripts/addEsFromScratch.sh
          ./devops-scripts/addEsFromScratch.sh
          fi
          branch_finish=$(git branch --show-current)
          echo "$branch_finish"