name: 'Validation using Scratch'
on:
  workflow_dispatch: 

jobs:
  validate-changes:
    name: CI Org Validation
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Validate Full Metadata
        id: full_validate
        run: |
          git config --global --add safe.directory "*"
          current_branch=$(git branch --show-current)
          echo "$current_branch"
          git fetch origin
          default_branch=$(git remote show origin | grep 'HEAD branch' | sed 's/.*: //')
          echo "$default_branch"

          chmod +x ./devops-scripts/es-exclude-forceignore.sh
          ./devops-scripts/es-exclude-forceignore.sh "$default_branch" "$current_branch"
          cat .forceignore
          echo "Simulating a failure condition"
          exit 1

      - name: Set Output Based on Step Result
        id: full_validate_result
        if: ${{ failure() && steps.full_validate.outcome == 'failure' }}
        run: echo "full_validation_failed=true" >> $GITHUB_OUTPUT

    outputs:
      full_validation_failed: ${{ steps.full_validate_result.outputs.full_validation_failed }}

  capture-error-message:
    name: Capture Error message
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_LINK: ${{ github.event.pull_request.html_url }}
      BRANCH_REF: ${{ github.ref }}
      environment: "MaxDevOps"
    needs: [ validate-changes ]
    if: ${{ always() && needs.validate-changes.outputs.full_validation_failed == 'true' && ! contains(needs.*.result, 'cancelled') }}
    steps:
      - name: Set Error Log
        run: |
          echo "run script set error"
          chmod +x ./devops-scripts/es-exclude-forceignore.sh
          ./devops-scripts/es-exclude-forceignore.sh "${{ env.BRANCH_REF }}" "original/develop"

