name: Compare Retrieved Metadata with Branch

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string

jobs:
  compare-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compare Metadata CI-Org and Develop Branch
        id: ci_org_es_changes
        run: |
          git config --global --add safe.directory "*"
          current_branch=${{ inputs.branch }}
          git fetch origin
          git checkout origin/develop
          #sf project retrieve start --metadata ExpressionSetDefinition --output-dir scratch_es --ignore-conflicts
          
          DIR1="scratch_es/main/default/expressionSetDefinition"
          DIR2="src/decision-centre/main/default/expressionSetDefinition"
          
          # Check if the retrieval command was successful
          if [ ! -d "$DIR1" ] || [ -z "$(ls -A "$DIR1")" ]; then
          echo "No data retrieved from Salesforce or directory is empty."
          echo "changed_files=" >> "$GITHUB_OUTPUT"
          exit 0
          fi
          
          # Run the diff command and get the list of changed files
          changed_files=$(diff -qr "$DIR1" "$DIR2" | grep -E '^Files ' | awk '{print $2}' | sed "s|^$DIR1/||")
          
          # Format the changed files to be space-separated on a single line
          formatted_changed_files=$(echo "$changed_files" | tr '\n' ' ')
          echo "$formatted_changed_files"
          echo "changed_files=$formatted_changed_files" >> "$GITHUB_OUTPUT"
          
          git checkout -- .
          git checkout "$current_branch

      - name: Handle Changes
        run: |
          echo "start addEsFromScratch"
          chmod +x ./devops-scripts/addEsFromScratch.sh
          ./devops-scripts/addEsFromScratch.sh "${{ steps.ci_org_es_changes.outputs.changed_files }}"