name: Compare Retrieved Metadata with Branch

on:
  workflow_call:
    inputs:
      auth_url:
        required: true
        type: string
        description: Auth URL of Org to be used for validation
    branch:
      required: false
      type: string

jobs:
  compare-metadata:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-full
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compare Metadata CI-Org and Develop Branch
        id: ci_org_es_changes
        run: |
          echo  s"${{ inputs.branch }}"
          chmod +x ./devops-scripts/findScratchChanges.sh
          ./devops-scripts/findScratchChanges.sh "${{ inputs.branch }}"
